import { writeFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { supabase } from "../supabase"
import { fetchCDragon, cdnUrl, LOCALES, LANG_COLUMNS, langIndex } from "./helpers"

interface CDragonChampion {
  id: number
  name: string
  description: string
  alias: string
  squarePortraitPath: string
  roles: string[]
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const I18N_DIR = resolve(__dirname, "../../../../packages/i18n/src")

export async function syncChampions() {
  if (!supabase) throw new Error("Supabase not configured")

  const results = await Promise.all(
    LOCALES.map((locale) => fetchCDragon<CDragonChampion[]>(locale, "champion-summary"))
  )

  const byId = new Map<
    number,
    { name_zh?: string; name_en?: string; name_ko?: string; alias: string; image_url: string | null; roles: string[] }
  >()

  for (let i = 0; i < results.length; i++) {
    const col = LANG_COLUMNS[langIndex(LOCALES[i])]
    for (const entry of results[i]) {
      if (!byId.has(entry.id)) {
        byId.set(entry.id, {
          alias: entry.alias,
          image_url: cdnUrl(entry.squarePortraitPath),
          roles: entry.roles ?? [],
        })
      }
      const row = byId.get(entry.id)!
      row[`name_${col}`] = entry.name
    }
  }

  const rows = Array.from(byId.entries()).map(([id, data]) => ({ id, ...data }))

  const { error } = await supabase.from("static_champions").upsert(rows, { onConflict: "id" })
  if (error) throw error

  generateTranslations(byId)
  return rows.length
}

function generateTranslations(byId: Map<number, { name_zh?: string; name_en?: string; name_ko?: string }>) {
  const entries: string[] = []
  for (const [, data] of byId) {
    if (!data.name_zh || data.name_zh === "无") continue
    const zh = JSON.stringify(data.name_zh)
    const en = JSON.stringify(data.name_en ?? "")
    const ko = JSON.stringify(data.name_ko ?? "")
    entries.push(`  ${zh}: [${en}, ${ko}]`)
  }

  const content = `// Auto-generated by pnpm sync --static
// CDragon champion-summary.json → static_champions
export const championNameMap: Record<string, [string, string]> = {
${entries.join(",\n")},
}

export function translateChampionName(zhName: string, locale: string): string {
  const entry = championNameMap[zhName]
  if (!entry) return zhName
  if (locale === "en") return entry[0]
  if (locale === "ko") return entry[1]
  return zhName
}
`

  writeFileSync(resolve(I18N_DIR, "data-translations.ts"), content, "utf-8")
  console.log(`  Generated data-translations.ts (${entries.length} champions)`)
}
