import { writeFileSync, readFileSync, existsSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { supabase } from "../supabase"
import { fetchCDragon, cdnUrl, LOCALES, LANG_COLUMNS, langIndex } from "./helpers"

interface CDragonAugment {
  id: number
  nameTRA: string
  augmentSmallIconPath: string
  rarity: string
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const I18N_DIR = resolve(__dirname, "../../../../packages/i18n/src")

function normalizeRarity(rarity: string): string {
  return rarity.replace(/^k/, "").toLowerCase()
}

export async function syncAugments() {
  if (!supabase) throw new Error("Supabase not configured")

  const results = await Promise.all(LOCALES.map((locale) => fetchCDragon<CDragonAugment[]>(locale, "cherry-augments")))

  const byId = new Map<
    number,
    { name_zh?: string; name_en?: string; name_ko?: string; icon_url: string | null; rarity: string }
  >()

  for (let i = 0; i < results.length; i++) {
    const col = LANG_COLUMNS[langIndex(LOCALES[i])]
    for (const entry of results[i]) {
      if (!byId.has(entry.id)) {
        byId.set(entry.id, {
          icon_url: cdnUrl(entry.augmentSmallIconPath),
          rarity: normalizeRarity(entry.rarity),
        })
      }
      const row = byId.get(entry.id)!
      row[`name_${col}`] = entry.nameTRA
    }
  }

  const rows = Array.from(byId.entries()).map(([id, data]) => ({ id, ...data }))

  const { error } = await supabase.from("static_augments").upsert(rows, { onConflict: "id" })
  if (error) throw error

  generateTranslations(byId)
  return rows.length
}

function generateTranslations(byId: Map<number, { name_zh?: string; name_en?: string; name_ko?: string }>) {
  // Build name maps from CDragon data
  const nameEnEntries: string[] = []
  const nameKoEntries: string[] = []

  const seenZh = new Set<string>()
  for (const [, data] of byId) {
    if (!data.name_zh || !data.name_en || seenZh.has(data.name_zh)) continue
    seenZh.add(data.name_zh)
    nameEnEntries.push(`  ${JSON.stringify(data.name_zh)}: ${JSON.stringify(data.name_en)}`)
  }
  seenZh.clear()
  for (const [, data] of byId) {
    if (!data.name_zh || !data.name_ko || seenZh.has(data.name_zh)) continue
    seenZh.add(data.name_zh)
    nameKoEntries.push(`  ${JSON.stringify(data.name_zh)}: ${JSON.stringify(data.name_ko)}`)
  }

  // Preserve existing description maps
  const existingDescEn = extractExistingMap("augmentDescEn")
  const existingDescKo = extractExistingMap("augmentDescKo")

  const descEnEntries = Object.entries(existingDescEn).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
  const descKoEntries = Object.entries(existingDescKo).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)

  const content = `// Auto-generated by pnpm sync --static
// CDragon cherry-augments.json → static_augments
export const augmentNameEn: Record<string, string> = {
${nameEnEntries.join(",\n")},
}

export const augmentNameKo: Record<string, string> = {
${nameKoEntries.join(",\n")},
}

// Description maps preserved from previous version (not auto-generated)
export const augmentDescEn: Record<string, string> = {
${descEnEntries.length > 0 ? descEnEntries.join(",\n") + "\n" : ""}}

export const augmentDescKo: Record<string, string> = {
${descKoEntries.length > 0 ? descKoEntries.join(",\n") + "\n" : ""}}

export function translateAugmentName(zhName: string, locale: string): string {
  if (locale === "en") return augmentNameEn[zhName] ?? zhName
  if (locale === "ko") return augmentNameKo[zhName] ?? zhName
  return zhName
}

export function translateAugmentDesc(zhDesc: string, locale: string): string {
  if (locale === "en") return augmentDescEn[zhDesc] ?? zhDesc
  if (locale === "ko") return augmentDescKo[zhDesc] ?? zhDesc
  return zhDesc
}
`

  writeFileSync(resolve(I18N_DIR, "augment-translations.ts"), content, "utf-8")
  console.log(`  Generated augment-translations.ts (${nameEnEntries.length} names, ${descEnEntries.length} descs)`)
}

function extractExistingMap(varName: string): Record<string, string> {
  const filePath = resolve(I18N_DIR, "augment-translations.ts")
  if (!existsSync(filePath)) return {}
  const source = readFileSync(filePath, "utf-8")
  const start = source.indexOf(`export const ${varName}`)
  if (start === -1) return {}
  const braceStart = source.indexOf("{", start)
  const braceEnd = source.indexOf("};", braceStart)
  if (braceStart === -1 || braceEnd === -1) return {}
  const body = source.slice(braceStart + 1, braceEnd)

  const map: Record<string, string> = {}
  for (const line of body.split("\n")) {
    const match = line.match(/^\s*(.+?):\s*(.+?),?\s*$/)
    if (!match) continue
    try {
      const key = JSON.parse(match[1])
      const val = JSON.parse(match[2])
      map[key] = val
    } catch {
      // skip unparseable lines
    }
  }
  return map
}
